// Reads the bot's OpenAPI document (/openapi.json, generated by FastAPI) into what the API page lists: endpoints
// grouped by tag, their parameters, and request bodies flattened to one row per field.

type Json = Record<string, unknown>

export interface Field {
  name: string
  /** `path`, `query` or `body`. */
  in: string
  type: string
  required: boolean
  description: string
}
export interface Endpoint {
  key: string
  method: string
  path: string
  tag: string
  /** First paragraph of the route's docstring; `description` is the whole of it. */
  summary: string
  description: string
  params: Field[]
  /** The request body's fields, or null when there's no body. */
  body: Field[] | null
  responses: { code: string; description: string }[]
}
export interface TagGroup {
  tag: string
  endpoints: Endpoint[]
}

// The bot's old server-rendered pages sit in the same app under the `web` tag; they aren't the API.
const HIDDEN_TAGS = new Set(['web'])
const TAG_ORDER = ['site', 'language', 'data', 'session', 'health', 'auth']
const METHODS = ['get', 'post', 'put', 'patch', 'delete']

function resolve(doc: Json, schema: unknown): Json {
  let s = (schema ?? {}) as Json
  for (let depth = 0; typeof s.$ref === 'string' && depth < 8; depth++) {
    const path = (s.$ref as string).replace(/^#\//, '').split('/')
    s = path.reduce<Json>((node, part) => (node?.[part] ?? {}) as Json, doc)
  }
  return s
}

/** A schema as a short type: `string ≤ 16`, `integer 0–5000`, `off | delete | timeout`, `string[]`. */
export function typeOf(doc: Json, schema: unknown): string {
  const s = resolve(doc, schema)
  const variants = (s.anyOf ?? s.oneOf) as unknown[] | undefined
  if (variants) {
    const types = variants.filter((v) => (v as Json).type !== 'null').map((v) => typeOf(doc, v))
    return types.join(' or ') || 'null'
  }
  if (Array.isArray(s.enum)) return (s.enum as unknown[]).map(String).join(' | ')
  if (s.type === 'array') return `${typeOf(doc, s.items)}[]`
  let type = typeof s.type === 'string' ? s.type : s.properties ? 'object' : 'any'
  const min = (s.minimum ?? s.minLength ?? s.minItems) as number | undefined
  const max = (s.maximum ?? s.maxLength ?? s.maxItems) as number | undefined
  if (min !== undefined && max !== undefined) type += ` ${min}–${max}`
  else if (max !== undefined) type += ` ≤ ${max}`
  else if (min !== undefined && min > 0) type += ` ≥ ${min}`
  return type
}

function bodyFields(doc: Json, operation: Json): Field[] | null {
  const content = (operation.requestBody as Json | undefined)?.content as Json | undefined
  if (!content) return null
  const media = (content['application/json'] ?? Object.values(content)[0]) as Json | undefined
  const schema = resolve(doc, media?.schema)
  const required = new Set((schema.required as string[] | undefined) ?? [])
  return Object.entries((schema.properties as Json | undefined) ?? {}).map(([name, prop]) => {
    const p = resolve(doc, prop)
    const fallback = p.default === undefined || p.default === null ? '' : `Default ${JSON.stringify(p.default)}.`
    return {
      name,
      in: 'body',
      type: typeOf(doc, prop),
      required: required.has(name),
      description: [p.description, fallback].filter(Boolean).join(' '),
    }
  })
}

export function readOpenApi(doc: Json): TagGroup[] {
  const groups = new Map<string, Endpoint[]>()
  for (const [path, item] of Object.entries((doc.paths as Json | undefined) ?? {})) {
    for (const method of METHODS) {
      const op = (item as Json)[method] as Json | undefined
      if (!op) continue
      const tag = ((op.tags as string[] | undefined) ?? ['other'])[0]!
      if (HIDDEN_TAGS.has(tag)) continue
      const description = ((op.description as string | undefined) ?? '').trim()
      const endpoint: Endpoint = {
        key: `${method} ${path}`,
        method: method.toUpperCase(),
        path,
        tag,
        summary: description.split(/\n\s*\n/)[0]!.replace(/\s+/g, ' ') || (op.summary as string | undefined) || '',
        description,
        params: ((op.parameters as Json[] | undefined) ?? []).map((p) => ({
          name: p.name as string,
          in: p.in as string,
          type: typeOf(doc, p.schema),
          required: Boolean(p.required),
          description: (p.description as string | undefined) ?? '',
        })),
        body: bodyFields(doc, op),
        responses: Object.entries((op.responses as Json | undefined) ?? {}).map(([code, r]) => ({
          code,
          description: ((r as Json).description as string | undefined) ?? '',
        })),
      }
      groups.set(tag, [...(groups.get(tag) ?? []), endpoint])
    }
  }
  const rank = (tag: string) => (TAG_ORDER.includes(tag) ? TAG_ORDER.indexOf(tag) : TAG_ORDER.length)
  return [...groups]
    .sort(([a], [b]) => rank(a) - rank(b) || a.localeCompare(b))
    .map(([tag, endpoints]) => ({ tag, endpoints }))
}

/** Text with `backticks` cut into plain and code runs, for docstrings. */
export function codeRuns(text: string): { text: string; code: boolean }[] {
  return text.split(/(`[^`]+`)/).filter(Boolean).map((part) =>
    part.startsWith('`') && part.endsWith('`') && part.length > 1 ? { text: part.slice(1, -1), code: true } : { text: part, code: false },
  )
}
